# Generated by Django 4.1.3 on 2022-12-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20221221_1010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(upload_to="static/images/"),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
