# Generated by Django 3.2.16 on 2022-12-19 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221219_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='theme',
            field=models.CharField(choices=[('sport', 'Спорт'), ('politic', 'Политика'), ('celebrity', 'Звезды'), ('art', 'Искусство'), ('fashion', 'Мода')], default=django.utils.timezone.now, max_length=255, verbose_name='Тематика'),
            preserve_default=False,
        ),
    ]
