# Generated by Django 4.1.3 on 2023-01-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_news_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_news",
                to="blog.news",
            ),
        ),
    ]
