# Generated by Django 4.1.3 on 2023-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_favorite_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(null=True, upload_to="static/images/"),
        ),
    ]
